# Generated by Django 4.0.6 on 2022-07-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='day_recurrency',
            field=models.IntegerField(max_length=2, verbose_name='Dia recorrente'),
        ),
    ]
