# Generated by Django 4.0.5 on 2022-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_difference',
            field=models.FloatField(default=0, verbose_name='Diferença total'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_expected_cost',
            field=models.FloatField(default=0, verbose_name='Total custo esperado'),
        ),
        migrations.AddField(
            model_name='category',
            name='total_real_cost',
            field=models.FloatField(default=0, verbose_name='Total custo real'),
        ),
    ]
