# Generated by Django 4.0.5 on 2022-06-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_total_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='spending',
            name='real_cost',
            field=models.FloatField(default=0, verbose_name='Custo real'),
        ),
    ]
